### ISSUE TITLE
识别oov的配置

### ISSUE THREAD

**Issue by Ivan-Ji** [GaoQ1/rasa_nlu_gq#20]
在训练的过程中，如何对未登录词进行识别呢。我这边的配置如下，
```
pipeline:
  - name: "MitieNLP"
    model: "total_word_feature_extractor_zh.dat"
  - name: "JiebaTokenizer"
  - name: "rasa_nlu_gao.extractors.bilstm_crf_entity_extractor.BilstmCRFEntityExtractor"
    lr: 0.001
    char_dim: 100
    lstm_dim: 100
    batches_per_epoch: 10
    seg_dim: 20
    num_segs: 4
    batch_size: 200
    tag_schema: "iobes"
    model_type: "idcnn"
    clip: 5
    optimizer: "adam"
    dropout_keep: 0.5
    steps_check: 300
  - name: "EntitySynonymMapper"
  - name: "RegexFeaturizer"
  - name: "CountVectorsFeaturizer"
  - name: "EmbeddingIntentClassifier"
```
查看了官方文档的RegexFeaturizer，没有发现可以调整的参数。而我针对CountVectorsFeaturizer使用token_pattern时，报出了如下的错误
```Cannot feed value of shape (64,) for Tensor 'a:0', which has shape '(?, 4232)'```
大佬方便解答一下吗
