### ISSUE TITLE
未登录词（OOV）的配置

### ISSUE THREAD

**Issue by Ivan-Ji** [GaoQ1/rasa_nlu_gq#21]
在使用rasa的过程中，想识别未登录词。我自己的配置如下
```
pipeline:
  - name: "MitieNLP"
    model: "total_word_feature_extractor_zh.dat"
  - name: "JiebaTokenizer"
  - name: "rasa_nlu_gao.extractors.bilstm_crf_entity_extractor.BilstmCRFEntityExtractor"
    lr: 0.001
    char_dim: 100
    lstm_dim: 100
    batches_per_epoch: 10
    seg_dim: 20
    num_segs: 4
    batch_size: 200
    tag_schema: "iobes"
    model_type: "idcnn"
    clip: 5
    optimizer: "adam"
    dropout_keep: 0.5
    steps_check: 300
  - name: "EntitySynonymMapper"
  - name: "RegexFeaturizer"
  - name: "CountVectorsFeaturizer"
  - name: "EmbeddingIntentClassifier"
```
我在RegexFeaturizer的源码没有找到相关参数的配置，大佬你写的代码里CountVectorsFeaturizer使用了token_pattern的参数，没加这个参数训练时可以正常训练，但加了自定义的token_pattern参数后，却报出了```Cannot feed value of shape (64,) for Tensor 'a:0', which has shape '(?, 52000)'```的错误。想问一下大佬有解决方案吗？或者能否提供一个解决未登录词（OOV）的解决方案？
