### ISSUE TITLE
KeyError: 'ner_bilstm'

### ISSUE THREAD

**Issue by red-frog** [GaoQ1/rasa_nlu_gq#6]
您好, 我在安装了您的repo后, 然后进行训练, 报错keyerror:
我使用的rasa_nlu版本是: v0.13.8

config.yml:

```


language: "zh"

pipeline:
- name: "tokenizer_jieba"
- name: "intent_featurizer_count_vectors"
  OOV_token: oov
  token_pattern: '(?u)\b\w+\b'
- name: "ner_bilstm_crf"
  lr: 0.001
  char_dim: 100
  lstm_dim: 100
  batches_per_epoch: 10
  seg_dim: 20
  num_segs: 4
  batch_size: 200
  tag_schema: "iobes"
  model_type: "bilstm" # 模型支持两种idcnn膨胀卷积模型或bilstm双向lstm模型
  clip: 5
  optimizer: "adam"
  dropout_keep: 0.5
  steps_check: 100
- name: "ner_synonyms"
- name: "jieba_pseg_extractor"
  part_of_speech: ["nr", "ns", "nt"]

- name: "intent_classifier_tensorflow_embedding"
path: "./models/inquiry_nlu"
data: "./data/data.json"


```

我还需要做别的什么配置吗?
